#ifndef PUEO_BIQUADS_H
#define PUEO_BIQUADS_H

//THIS FILE IS AUTOGENERATED

#define PUEO_BIQUAD_F_NUM 401
#define PUEO_BIQUAD_F_MIN 200
#define PUEO_BIQUAD_F_MAX 600
#define PUEO_BIQUAD_F_STEP 1
#define PUEO_BIQUAD_Q_NUM 20
#define PUEO_BIQUAD_Q_MIN 1
#define PUEO_BIQUAD_Q_MAX 20
#define PUEO_BIQUAD_Q_STEP 1


#include <stdint.h>

typedef struct pueo_biquad
{
  int32_t B;
  int32_t A;
  int32_t C[4];
  int32_t a1, a2;
  int32_t D_FF;
  int32_t F[2];
  int32_t E_GG;
  int32_t G[3];
  int32_t D_FG;
  int32_t E_GF;
} pueo_biquad_t;

#define PUEO_BIQUAD_QINDEX(Q)  (( Q-PUEO_BIQUAD_Q_MIN) / PUEO_BIQUAD_Q_STEP )
#define PUEO_BIQUAD_FINDEX(F)  (( F-PUEO_BIQUAD_F_MIN) / PUEO_BIQUAD_F_STEP )

 #endif

